
# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - echo ajek appveyor test

  build:
    parallel: true                  # enable MSBuild parallel builds
    project: MyTestAzureCS.sln      # path to Visual Studio solution or project

    