
# version format
version: 1.0.{build}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  cmd: echo ajek appveyor test v2

# Build worker image (VM template)
image: Visual Studio 2017

build:
  parallel: true                  # enable MSBuild parallel builds
  project: rpgcraft.sln

